In [10]:
import pandas as pd

In [6]:
a = [(763.1666666666666, 801.1, 799.5166666666667), (686.8555555555556, 843.875, 820.0), (733.0, 833.75, 828.0), (658.75, 700.8333333333334, 744.5), (786.8166666666667, 855.8, 809.3), (714.0, 820.75, 843.0), (738.6666666666666, 805.3333333333334, 818.0), (726.8333333333333, 829.8333333333334, 841.8333333333333), (794.2916666666666, 904.5, 900.75), (817.75, 821.75, 820.0), (641.1333333333333, 724.25, 742.0), (735.125, 745.375, 741.125), (730.5, 786.75, 782.8333333333334), (692.0, 756.0, 787.0), (636.3, 742.5, 772.5), (536.25, 751.063492063492, 713.7777777777778), (692.75, 802.0, 789.0), (721.1515151515151, 886.0833333333333, 871.3333333333333), (693.1666666666666, 757.2666666666668, 725.5), (756.8333333333333, 820.3333333333333, 785.3333333333333), (695.6666666666666, 784.9166666666666, 836.0), (492.9659090909091, 613.5861471861472, 588.2575757575758), (769.5, 795.875, 781.0), (797.5, 843.0, 794.0), (619.7, 756.3, 724.875), (598.9583333333333, 739.6666666666666, 777.8333333333333), (778.0, 800.5454545454545, 801.3636363636364), (784.8888888888889, 800.5, 798.0), (717.5, 792.5, 783.5), (805.25, 822.25, 815.5), (753.0, 790.0, 819.0), (507.72222222222223, 595.8888888888889, 618.2777777777778)]

In [11]:
haha = pd.DataFrame(a)

In [12]:
haha

             0           1           2
0   763.166667  801.100000  799.516667
1   686.855556  843.875000  820.000000
2   733.000000  833.750000  828.000000
3   658.750000  700.833333  744.500000
4   786.816667  855.800000  809.300000
5   714.000000  820.750000  843.000000
6   738.666667  805.333333  818.000000
7   726.833333  829.833333  841.833333
8   794.291667  904.500000  900.750000
9   817.750000  821.750000  820.000000
10  641.133333  724.250000  742.000000
11  735.125000  745.375000  741.125000
12  730.500000  786.750000  782.833333
13  692.000000  756.000000  787.000000
14  636.300000  742.500000  772.500000
15  536.250000  751.063492  713.777778
16  692.750000  802.000000  789.000000
17  721.151515  886.083333  871.333333
18  693.166667  757.266667  725.500000
19  756.833333  820.333333  785.333333
20  695.666667  784.916667  836.000000
21  492.965909  613.586147  588.257576
22  769.500000  795.875000  781.000000
23  797.500000  843.000000  794.000000
24  619.700000  756.300000  724.875000
25  598.958333  739.666667  777.833333
26  778.000000  800.545455  801.363636
27  784.888889  800.500000  798.000000
28  717.500000  792.500000  783.500000
29  805.250000  822.250000  815.500000
30  753.000000  790.000000  819.000000
31  507.722222  595.888889  618.277778